### ISSUE TITLE
How I can import DatePickerModule and OverlayModule with "Angular Cli" ?.

### ISSUE THREAD

**Issue by tnqsoft** [rd-dev-ukraine/angular-io-datepicker#1]
Hi !

Thanks for share Datepicker component, but...How I can import DatePickerModule and OverlayModule with "Angular Cli" ?.

**Comment by rd-dev-ukraine** [comment]
@tnqsoft What kind of problem you have got?

**Comment by Taewa** [comment]
I have a similar question.
Where to import `OverlayModule` and `DatePickerModule`?

**Comment by Taewa** [comment]
Ok it was

```
import { DatePickerModule } from "angular-io-datepicker/src/datepicker/index";
import { OverlayModule } from "angular-io-overlay";
```

And had to install `OverlayModule` myself. ( `npm i angular-io-overlay --save`)

**Comment by issunboshi** [comment]
Thanks @Taewa. The readme should mention how to get hold of the OverlayModule

**Comment by Taewa** [comment]
@issunboshi I agree.
