### ISSUE TITLE
<template> element deprecation warning 

### ISSUE THREAD

**Issue by DmytroStepaniuk** [rd-dev-ukraine/angular-io-datepicker#17]
So, angular complains on <template> element that comes from OverlayModule i guess 

```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[WARNING ->]<template #container></template>"): ng:///OverlayModule/OverlayComponent.html@0:0
```

But it still works. It would be great to prevent problems about deprecated stuff.

**Comment by eugenesaenko** [comment]
Please update angular-io-overlay to 1.2.8.
