### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by a2ron44** [rd-dev-ukraine/angular-io-datepicker#23]
What is the best way to change the font/styling of this component?  I cannot seem to overwrite the default stying.  Would it be possible to leave font as inherited?

**Comment by KogaSilverDragon** [comment]
I had the same problem and this solution worked for me. In your component CSS you may do "shadow piercing".
Reference: https://stackoverflow.com/questions/34542143/load-external-css-style-into-angular-2-component
`:host /deep/ .datepicker-actions__input {
    font-family: Arial !important;
}`
