### ISSUE TITLE
Restricting manual enter of date and time

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [rd-dev-ukraine/angular-io-datepicker#35]
How to restrict user from entering or modifying date and time manually.

**Comment by eugenesaenko** [comment]
Use disabled flag

**Comment by HarshaVardhanPVK** [comment]
Hi, if I set disabled flag to true then datepicker is also getting disabled, but I only want to restrict 
manual modification in text box and datepicker should work normally.
