### ISSUE TITLE
angular io picker issue while building

### ISSUE THREAD

**Issue by vignesh2694** [rd-dev-ukraine/angular-io-datepicker#37]
ERROR in Error encountered resolving symbol values statically. Calling function 'ControlValueAccessorProviderFactory', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DatePicker in /var/www/html/AmyPro/angular/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts, resolving symbol DatePicker in /var/www/html/AmyPro/angular/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/html/AmyPro/angular/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

this is the error i am getting while **ng build --prod --aot=true**
but it is compiling successfull in **ng serve**
------------------------------------------------------------------------------------------------------------------------------------------
npm version:5.6.0
node version: v6.11.5

-------------------------------------------------------------------------------------------------------------------------------------------
angular/cli: 1.2.4
node: 6.11.5
os: linux ia32
angular/animations: 4.4.4
angular/cdk: 2.0.0-beta.11
angular/common: 4.4.4
angular/compiler: 4.4.4
angular/core: 4.4.4
angular/forms: 4.4.4
angular/http: 4.4.4
angular/material: 2.0.0-beta.11
angular/platform-browser: 4.4.4
angular/platform-browser-dynamic: 4.4.4
angular/router: 4.4.4
angular/cli: 1.2.4
angular/compiler-cli: 4.4.4

-------------------------------------------------------------------------------------------------------------------------------------------
package.json
 "name": "angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "angular/animations": "^4.4.4",
    "angular/cdk": "^2.0.0-beta.10",
    "angular/common": "^4.4.4",
    "angular/compiler": "^4.4.4",
    "angular/core": "^4.4.4",
    "angular/forms": "^4.4.4",
    "angular/http": "^4.4.4",
    "angular/material": "^2.0.0-beta.10",
    "angular/platform-browser": "^4.4.4",
    "angular/platform-browser-dynamic": "^4.4.4",
    "angular/router": "^4.4.4",
    "angular-io-datepicker": "^1.3.1",
    "angular2-csv": "^0.2.5",
    "angular2-http-file-upload": "^1.0.6",
    "angular2-jwt": "^0.2.3",
    "angular2-text-mask": "^8.0.4",
    "angular4-datepicker": "^1.0.1",
    "bootstrap": "^4.0.0-beta",
    "chart.js": "^2.7.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "jquery": "^3.2.1",
    "mydatepicker": "^2.6.1",
    "ng2-charts": "^1.6.0",
    "ng2-ckeditor": "^1.1.9",
    "ng2-file-upload": "^1.2.1",
    "ng2-filter-pipe": "^0.1.10",
    "ng2-validation": "^4.2.0",
    "ngx-pagination": "^3.0.1",
    "popper.js": "^1.12.5",
    "rxjs": "^5.4.3",
    "tether": "^1.4.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "angular/cli": "1.2.4",
    "angular/compiler-cli": "^4.4.4",
    "types/jasmine": "2.5.38",
    "types/node": "^6.0.88",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }

**Comment by eugenesaenko** [comment]
duplicate #15
