### ISSUE TITLE
datepicker.css (404) not found issue

### ISSUE THREAD

**Issue by merey90** [rd-dev-ukraine/angular-io-datepicker#4]
First of all, your datepicker looks great, simple and flexible, and I like it very much!
But here is my issue:

In angular-cli v1.0.0 with angular v4.0.0 getting this error "Unhandled Promise rejection: Failed to load ../datepicker.css" and "GET http://localhost:4200/datepicker.css 404 (Not Found)" from zone.js.

Full [package.json](https://drive.google.com/open?id=0B-3lh_Fa6X4KbXVSWjBxV2t1Tjg)

**Comment by rd-dev-ukraine** [comment]
@merey90 we fixed it. Please update package to version 1.2.3
