### ISSUE TITLE
not inserting date in database through template driven form approach.

### ISSUE THREAD

**Issue by aruribadraiah** [rd-dev-ukraine/angular-io-datepicker#8]
my html file is
<div class="form-group">
           <date-picker class="form-control" name="dob" format="YYYY-MM-DD" formControlName="dob"></date-picker>
</div>
ts file
   dob = new FormControl('');
   this.addCatForm = this.formBuilder.group({
         dob:this.dob
    });                                       /* model file is  */
import * as mongoose from 'mongoose';
const catSchema = new mongoose.Schema({
      dob:Date
});

kindly help for not inserting date in the database.

**Comment by eugenesaenko** [comment]
Datepicker sets date in UTC format like `2017-07-05T00:00:00.000Z`. Just sent this value to server and store it like string.
